---
- name: install check scripts
  template:
    src: check-service-active.j2
    dest: /usr/local/bin/check-service-active
    mode: u=rwx,g=rx,o=rx
  tags:
    - utils

- apt:
    name: htop
    update_cache: yes
  with_items:
    - htop
    - dnsutils
    - telnet
    - curl
    - net-tools
    - unzip
    - htop
    - wget
  tags:
    - utils

- name: Create mounted Movies directory
  file:
    path: /mnt/movies
    state: directory
- name: Remove existing mount for movies
  mount:
    name: /mnt/movies
    state: unmounted
- name: Mount movies directory
  mount:
    name: /mnt/movies
    src: "//192.168.1.43/USBDisk1/Movies"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root

- name: Create mounted MoviesSync directory
  file:
    path: /mnt/movies-sync
    state: directory
- name: Remove existing mount for moviesSync
  mount:
    name: /mnt/movies-sync
    state: unmounted
- name: Mount moviessync directory
  mount:
    name: /mnt/movies-sync
    src: "//192.168.1.43/USBDisk1/Sync"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root

- name: Create mounted TV directory
  file:
    path: /mnt/tv
    state: directory
- name: Remove existing mount for TV
  mount:
    name: /mnt/tv
    state: unmounted
- name: Mount tv directory
  mount:
    name: /mnt/tv
    src: "//192.168.1.43/USBDisk2/TV Shows"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root

- name: Create mounted TVSync directory
  file:
    path: /mnt/tv-sync
    state: directory
- name: Remove existing mount for TVSync
  mount:
    name: /mnt/tv-sync
    state: unmounted
- name: Mount tv directory
  mount:
    name: /mnt/tv-sync
    src: "//192.168.1.43/USBDisk2/Sync"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root

- name: Create mounted config directory
  file:
    path: /mnt/configs
    state: directory
- name: Remove existing mount for configs
  mount:
    name: /mnt/configs
    state: unmounted
- name: Mount configs directory
  mount:
    name: /mnt/configs
    src: "//192.168.1.43/Public/NomadConfigs"
    opts: "noacl,uid=pi,gid=docker,username=admin,password=admin"
    fstype: cifs
    state: mounted
  become: true # as root
